/**
 * Generates `legacyScoringLock.generated.ts` -- the committed fingerprint
 * baseline `checkScoringLockIntegrity.ts` diffs the CURRENT build against
 * to catch accidental drift on production people who predate the
 * candidate-JSON pipeline and therefore have no `data-pipeline/
 * candidates/*.json` file for the JSON-diff check to compare against
 * (see docs/checkpoints/match-pool-integrity-post-roster32.md and
 * docs/checkpoints/legacy-integrity-kurosawa-remediation.md).
 *
 * This is a baseline snapshot, not row-level provenance: it does NOT
 * claim a written rationale exists for these rows (most don't -- that is
 * the documented finding this tool exists to guard against getting
 * WORSE, not a claim it has been fixed for everyone). Re-run this
 * generator, and commit the result, in the SAME PR that documents an
 * intentional change to one of these people (per this project's existing
 * NEW_EVIDENCE/RUBRIC_CORRECTION/ERROR_CORRECTION discipline) -- never as
 * a silent, undocumented "just regenerate it" fix.
 *
 * Usage: corepack pnpm@10 exec tsx src/dev/roster1000/audits/generateLegacyScoringLock.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SEED_PEOPLE } from "../../../data/people/seed.js";
import { buildInventory } from "./matchPoolIntegrityAudit.js";

const OUT_PATH = join(process.cwd(), "src/dev/roster1000/audits/legacyScoringLock.generated.ts");

function tsString(s: string): string {
  return JSON.stringify(s);
}

function main(): void {
  const inventory = buildInventory(SEED_PEOPLE);
  const legacySlugs = inventory.filter((r) => !r.hasCandidateFile).map((r) => r.slug).sort();

  const entries = legacySlugs.map((slug) => {
    const person = SEED_PEOPLE.find((p) => p.slug === slug)!;
    const rows = [...person.attributes]
      .sort((a, b) => a.attributeId.localeCompare(b.attributeId))
      .map(
        (a) =>
          `    { attributeId: ${tsString(a.attributeId)}, score: ${a.score}, confidence: ${a.confidence}, evidenceType: ${tsString(a.evidenceType)}, impact: ${tsString(a.impact)} },`,
      )
      .join("\n");
    return `  ${tsString(slug)}: [\n${rows}\n  ],`;
  });

  const totalRows = legacySlugs.reduce((s, slug) => s + SEED_PEOPLE.find((p) => p.slug === slug)!.attributes.length, 0);
  const source = `/**
 * GENERATED by generateLegacyScoringLock.ts -- do not hand-edit.
 *
 * Fingerprint baseline (attributeId/score/confidence/evidenceType/impact)
 * for every production person with no data-pipeline/candidates JSON file,
 * as of the commit that generated this file. See that script's header
 * comment for what this guards against and how to regenerate it.
 *
 * Regenerated: ${new Date().toISOString().slice(0, 10)}. ${entries.length} people, ${totalRows} total rows.
 */
import type { AttributeId } from "../../../core/attributes/attributes.js";

export interface LegacyRowFingerprint {
  attributeId: AttributeId;
  score: number;
  confidence: number;
  evidenceType: string;
  impact: string;
}

export const LEGACY_SCORING_BASELINE: Readonly<Record<string, readonly LegacyRowFingerprint[]>> = {
${entries.join("\n")}
};
`;

  writeFileSync(OUT_PATH, source, "utf8");
  console.log(`Wrote ${legacySlugs.length} legacy people (${legacySlugs.reduce((s, slug) => s + SEED_PEOPLE.find((p) => p.slug === slug)!.attributes.length, 0)} rows) to ${OUT_PATH}`);
}

main();
